name: chat-app

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-networks

  backend:
    build: ./backend
    # image: jvamtruong/chat-app-backend:1.1
    container_name: node-api
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - mern-networks

  frontend:
    build: ./frontend
    # image: jvamtruong/chat-app-frontend:1.0
    container_name: react-ui
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - mern-networks

volumes:
  mongo-data:

networks:
  mern-networks:
    driver: bridge